name: iv_project_core
description: "IV Project Core"
version: 0.1.0
homepage:
publish_to: "none"

environment:
  sdk: ^3.10.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  go_router: ^17.0.1
  flutter_bloc: ^9.1.1
  intl: ^0.20.2
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  assets:
    - assets/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Nunito-Black.ttf
          weight: 900

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700

        - asset: assets/fonts/Inter-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Inter-RegularItalic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Inter-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Inter-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Inter-BoldItalic.ttf
          weight: 700
          style: italic

    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf

    - family: ArefRuqaa
      fonts:
        - asset: assets/fonts/ArefRuqaa-Regular.ttf
          weight: 400
        - asset: assets/fonts/ArefRuqaa-Bold.ttf
          weight: 700
