name: iv_project_core
description: "IV Project Core"
version: 0.0.8
homepage:
publish_to: 'none'

environment:
  sdk: ^3.10.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  go_router: ^17.0.0

  flutter_bloc: ^9.1.1

  intl: ^0.20.2

  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  assets:
    - assets/
    
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700

        - asset: assets/fonts/Inter-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Inter-RegularItalic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Inter-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Inter-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Inter-BoldItalic.ttf
          weight: 700
          style: italic
    
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
    
    - family: ArefRuqaa
      fonts:
        - asset: assets/fonts/ArefRuqaa-Regular.ttf
          weight: 400
        - asset: assets/fonts/ArefRuqaa-Bold.ttf
          weight: 700